---
title: "Shinyapp - NPM"
output: html_document
date: "2023-03-13"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Shinyapp for Net Profit Margin of the top 100 companies

## Mutating the profit/sales column for net profit margin 
```{r}
companies_NPM <- companies %>% 
  mutate(net_profit_margin_percent = profit_bil/sales_bil *100) %>% 
  filter(global_company != "Bradespar") %>% 
  arrange(-net_profit_margin_percent) %>%
  head(100)
companies_NPM
```

```{r}
#write.csv("companies_NPM.csv", row.names = F)
```

## Base plots for the app (NPM)
```{r}
companies_NPM %>%
  ggplot(aes(x=profit_bil, y=sales_bil)) + 
  geom_point()
```

```{r}
companies_NPM %>%
  count(country) %>%
  arrange(-n)
```

```{r}
#install.packages("shinydashboard")
library(shinydashboard)
```

```{r, eval=F, echo=T}
library(shiny)
library(shinydashboard)
ui <- dashboardPage(
  dashboardHeader(title="NPM by Country"),
  dashboardSidebar(disable=T),
  dashboardBody(
    fluidRow(
      box(
        selectInput("x", "Select Country", 
                    choices = c("United States", "Sweden", "Canada", "China", "Hong Kong", "United Kingdom", "Germany", "France", "Saudi Arabia", "Switzerland"), 
                    selected = "United States"),
        sliderInput("pointsize", "Select the Point Size", min=.5, max=5, value=2.5, step=.5)
      ),
      
      box(
        plotOutput("plot", width="600px", height= "500px"))
    )
  )
)


server <- function(input, output, session) {
  session$onSessionEnded(stopApp)
  output$plot <- renderPlot({
    companies_NPM %>%
      filter(country==input$x) %>%
      ggplot(aes(x=profit_bil, y=sales_bil, color=country)) + 
      geom_point(size=input$pointsize) +
      theme_light() + 
      labs(
        x = "Profit (Billions)",
        y = "Sales (Billions)")
    
  })
  
}

shinyApp(ui, server)
```

